RF-22209 Get tests to pass
This was passing earlier, but then started failing due to:
> ReferenceError: Cannot access 'root' before initialization

I'm not sure what I changed, but this gets the tests passing again locally 🤔